BEGIN

INSERT INTO "question" ("description", "goodResponseId")
VALUES
('Parmi les éléments de cette liste, lesquels sont des frameworks ou bibliothèques JavaScript ?',3 ),
('React est un excellent outil pour :', 6),
('Que doit-on écrire en CSS pour appliquer un style aux balises de titre de niveau 2 et 3 ?', 12),
('Lequel de ces alignements fait prendre au texte toute la largeur disponible ?', 16),
('Laquelle de ces couleurs correspond à du blanc ?', 19),
('Laquelle de ces balises indique un pied de page ?', 21),
('Laquelle de ces balises représente une ligne dans un tableau ?', 21),
('Quelle est la méthode d''envoi de formulaire la plus recommandée qui permet d''envoyer le plus de données ?', 24),
('L''adresse complète et le numéro de téléphone des sociétés et organisations', 28),
('Dans un site web  le format de date', 31);

INSERT INTO "answer" ("id", "name","questionId")
VALUES
('PHP', 1),
('Symfony', 1),
('ReactJs', 1),
('HTML', 1),
('créer des bases de données.', 2),
('construire une interface utilisateur à partir de composants réutilisables.', 2),
('créer un algorithme de machine learning.', 2),
('créer le design d une maquette.', 2),
('h2 + h3', 3),
('h2 h3', 3),
('.h2 .h3', 3),
('h2, h3', 3),
('left', 4),
('center', 4),
('right',4),
('justify', 4),
('#000', 5),
('rgb(100, 100, 100)', 5),
('#FFFFFF', 5),
('purple', 5),
('<footer>', 6),
('<bottom>', 6),
('<nav>', 6),
('<div>', 6),
('<tr>', 7),
('<table>', 7),
('<line>', 7),
('<td>', 7),
('get', 8),
('action', 8),
('post', 8),
('submit', 8),
('Sont indiquées dans chaque pied de page.', 9),
('Sont indiquées dans la page des Mentions légales.', 9),
('Sont indiquées dans la page Contact.', 9),
('Sont disponibles depuis toutes les pages du site.', 9),
('n''a pas d importance.', 10),
('Doit correspondre au format iso du pays de publication.', 10),
('Doit être un format explicite.', 10),
('Doit être " jour/mois/année ".', 10),

COMMIT;
